### ISSUE TITLE
User password storage is flawed (UPDATED)

### ISSUE THREAD

**Issue by marco-calautti** [ferdium/ferdium-server#42]
From what I can see, you simply store the hash of the user password in the database, without any salt (e.g., the timestamp). This makes the passwords weak to bruteforce, or rainbow table-based attacks, if the user uses a sufficiently short password.

You should consider salting the user's password with a random, long string, that you store for each user.

**Comment by marco-calautti** [comment]
Nevermind, I see you are using bcrypt, which should automatically generate and incorporate the salt in the hashed password.

**Comment by SpecialAro** [comment]
> Nevermind, I see you are using bcrypt, which should automatically generate and incorporate the salt in the hashed password.

Closing the issue as per this statement. Feel free to reopen it if you think I shouldn't.
