### ISSUE TITLE
Publish multi-arch images

### ISSUE THREAD

**Issue by lnhrdt** [ferdium/ferdium-server#45]
I'm trying to migrate from ferdi-server. Ferdi-server published multi-arch images that included `linux/amd64` and `linux/arm64`. The ferdium-server images only contain `linux/amd64` so I'm unable to run the image on my ARM arch hardware.

Any chance you could start publishing multi-arch images that support ARM, like Ferdi did?

**Comment by cino** [comment]
Sounds like something we should do. Don't have a timeline on it, but it's coming in the future.

**Comment by lnhrdt** [comment]
Thanks for the quick response @cino. Would the team be open to a contribution from me on this? I have experience setting this up and it looks like things are already really well setup in the existing docker GitHub Actions workflow.
https://github.com/ferdium/ferdium-server/blob/main/.github/workflows/docker.yml

**Comment by lnhrdt** [comment]
@cino I took a closer look at the workflow and saw that this is probably as simple as a configuration change. I went ahead and made a PR. I'll move the rest of my thoughts to the convo over there.

**Comment by mzayn** [comment]
follow on this issue - want to know when arms linux server can work with ferdium-server. thanks
