### ISSUE TITLE
API Path

### ISSUE THREAD

**Issue by muddro1** [ferdium/ferdium-server#54]
I have a self-hosted server. I do not like the idea of having my instance exposed without authentication I have set up on my reverse proxy, however, then my clients will not be able to log in. Is there an api path I can leave exposed while protecting the rest?

**Comment by SpecialAro** [comment]
Hi @muddro1 

What exactly do you want to accomplish by that? You can expose this service and disable the dashboard (look for the documentation) interface without needing to add a basic (or other kind of authentication) to the service.

I'm closing this issue as it is old. Feel free to comment below to re-open it.
