### ISSUE TITLE
Can't use headset or webcam

### ISSUE THREAD

**Issue by Falciform** [ferdium/ferdium-server#59]
Hi

Is there a know reason why i'm unable to use my headset and webcam from within Ferdium?
Everything else seems to work. I've enabled webRTC also but nothing changes.

**Comment by Falciform** [comment]
sorry. Wrong place. My bad!

**Comment by SpecialAro** [comment]
Hello @Falciform , please open this issue in the correct place (as you stated).

Thank you!
