### ISSUE TITLE
'SSL_ERROR_RX_RECORD_TOO_LONG' when trying to connect via HTTPS?

### ISSUE THREAD

**Issue by ojhernandez** [ferdium/ferdium-server#65]
I'm working on setting up ferdium-server and so far, everything appears to have worked well but right now, I can only access it via HTTP at http://<MYURL>.com:3333.

When I visit https://<MYURL>.com:3333, Firefox tells me, "Secure Connection Failed" with an Error Code of "SSL_ERROR_RX_RECORD_TOO_LONG"

In the docker compose file, I've tried setting `DB_SSL` to `true` but get the same issue.

I'm unsure how to go about troubleshooting this and figured I'd start here. I've configured other web apps in Docker with my SSL certificate so I assumed it was something on my end in configuring ferdium-server that I'm missing.

I'd greatly appreciate any help; thanks!

**Comment by SpecialAro** [comment]
Hi @ojhernandez !

Would you be able to post this issue on discord instead (given this is a bit out of scope of the project - is more devOps on your side) ?
I'm happy to try and help you with this. Just ping me or DM me there.

Discord link: https://discord.gg/jVv4Qns8pP
