### ISSUE TITLE
Packages settings for PR#1

### ISSUE THREAD

**Issue by Gibby** [ferdium/ferdium-server#8]
I forgot for https://github.com/ferdium/ferdium-server/pull/1 that a few settings need updated on GitHub.

By default I think GitHub makes packages private.

It will need to be switched to Public and the repo will also need write access under `Manage Actions access`

This should be the URL to update the settings https://github.com/org/ferdium/packages/container/ferdium-server/settings

**Comment by mydarkstar** [comment]
@dqos As you're the organization owner, could you please check this and close the issue?

**Comment by dqos** [comment]
@Gibby I adjusted the Packages settings under the org to Public. Where and how can I adjust the Manage Action access?
Your URL ends up in a 404 😄

**Comment by Gibby** [comment]
Dang, I thought that would be the URL for a package for an org. I just noticed an issue with the action, I'll push a PR in a few.

**Comment by Gibby** [comment]
@dqos under manager access there should be a check box to make it the same permissions as the repo. And also there is an action permission that needs to be set to read & write.
